# Generated by Django 4.0.4 on 2022-04-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500, unique=True)),
                ('ProductPrice', models.IntegerField()),
                ('ProductPhotoFileName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserProductsMappings',
            fields=[
                ('MappingId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=500, unique=True)),
                ('FirstName', models.CharField(max_length=500)),
                ('LastName', models.CharField(max_length=500)),
                ('Password', models.CharField(max_length=500, unique=True)),
            ],
        ),
    ]
