# Generated by Django 4.0.4 on 2022-04-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntiretyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('RoleId', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserRolesMappings',
            fields=[
                ('MappingId', models.AutoField(primary_key=True, serialize=False)),
                ('UserId', models.IntegerField()),
                ('RoleId', models.IntegerField()),
            ],
        ),
    ]
